// <auto-generated />
using System;
using CinemaPlus.CinemaWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaPlus.CinemaWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430043604_SeedMoreDemoBookedSeats")]
    partial class SeedMoreDemoBookedSeats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.BookedSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("BookingId", "SeatId")
                        .IsUnique();

                    b.HasIndex("SessionId", "SeatId")
                        .IsUnique();

                    b.ToTable("BookedSeats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            SeatId = 25,
                            SessionId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 1,
                            SeatId = 26,
                            SessionId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 2,
                            SeatId = 14,
                            SessionId = 5
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 2,
                            SeatId = 15,
                            SessionId = 5
                        },
                        new
                        {
                            Id = 5,
                            BookingId = 3,
                            SeatId = 73,
                            SessionId = 7
                        },
                        new
                        {
                            Id = 6,
                            BookingId = 3,
                            SeatId = 74,
                            SessionId = 7
                        },
                        new
                        {
                            Id = 7,
                            BookingId = 3,
                            SeatId = 75,
                            SessionId = 7
                        },
                        new
                        {
                            Id = 8,
                            BookingId = 4,
                            SeatId = 173,
                            SessionId = 20
                        },
                        new
                        {
                            Id = 9,
                            BookingId = 4,
                            SeatId = 174,
                            SessionId = 20
                        },
                        new
                        {
                            Id = 10,
                            BookingId = 5,
                            SeatId = 86,
                            SessionId = 3
                        },
                        new
                        {
                            Id = 11,
                            BookingId = 5,
                            SeatId = 87,
                            SessionId = 3
                        },
                        new
                        {
                            Id = 12,
                            BookingId = 5,
                            SeatId = 98,
                            SessionId = 3
                        },
                        new
                        {
                            Id = 13,
                            BookingId = 5,
                            SeatId = 99,
                            SessionId = 3
                        },
                        new
                        {
                            Id = 14,
                            BookingId = 6,
                            SeatId = 109,
                            SessionId = 8
                        },
                        new
                        {
                            Id = 15,
                            BookingId = 6,
                            SeatId = 110,
                            SessionId = 8
                        },
                        new
                        {
                            Id = 16,
                            BookingId = 6,
                            SeatId = 121,
                            SessionId = 8
                        },
                        new
                        {
                            Id = 17,
                            BookingId = 7,
                            SeatId = 31,
                            SessionId = 16
                        },
                        new
                        {
                            Id = 18,
                            BookingId = 7,
                            SeatId = 32,
                            SessionId = 16
                        },
                        new
                        {
                            Id = 19,
                            BookingId = 7,
                            SeatId = 33,
                            SessionId = 16
                        },
                        new
                        {
                            Id = 20,
                            BookingId = 8,
                            SeatId = 189,
                            SessionId = 23
                        },
                        new
                        {
                            Id = 21,
                            BookingId = 8,
                            SeatId = 190,
                            SessionId = 23
                        },
                        new
                        {
                            Id = 22,
                            BookingId = 8,
                            SeatId = 195,
                            SessionId = 23
                        });
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingDate");

                    b.HasIndex("SessionId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 5, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "client@cinemaplus.local",
                            CustomerName = "Олена Коваль",
                            CustomerPhone = "+380672223344",
                            SessionId = 1,
                            Status = "Paid",
                            TicketCode = "CP-20260501-0001",
                            TotalPrice = 360m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2026, 5, 2, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "client@cinemaplus.local",
                            CustomerName = "Олена Коваль",
                            CustomerPhone = "+380672223344",
                            SessionId = 5,
                            Status = "Paid",
                            TicketCode = "CP-20260502-0002",
                            TotalPrice = 360m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookingDate = new DateTime(2026, 5, 3, 18, 20, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "marina.demo@cinemaplus.local",
                            CustomerName = "Марина Стеценко",
                            CustomerPhone = "+380931110022",
                            SessionId = 7,
                            Status = "Paid",
                            TicketCode = "CP-20260503-0003",
                            TotalPrice = 660m
                        },
                        new
                        {
                            Id = 4,
                            BookingDate = new DateTime(2026, 5, 4, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "igor.demo@cinemaplus.local",
                            CustomerName = "Ігор Мельник",
                            CustomerPhone = "+380661230045",
                            SessionId = 20,
                            Status = "Paid",
                            TicketCode = "CP-20260504-0004",
                            TotalPrice = 520m
                        },
                        new
                        {
                            Id = 5,
                            BookingDate = new DateTime(2026, 5, 5, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "nataliia.demo@cinemaplus.local",
                            CustomerName = "Наталія Гринь",
                            CustomerPhone = "+380971230056",
                            SessionId = 3,
                            Status = "Paid",
                            TicketCode = "CP-20260505-0005",
                            TotalPrice = 880m
                        },
                        new
                        {
                            Id = 6,
                            BookingDate = new DateTime(2026, 5, 5, 16, 35, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "client@cinemaplus.local",
                            CustomerName = "Олена Коваль",
                            CustomerPhone = "+380672223344",
                            SessionId = 8,
                            Status = "Paid",
                            TicketCode = "CP-20260505-0006",
                            TotalPrice = 660m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            BookingDate = new DateTime(2026, 5, 6, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "andrii.demo@cinemaplus.local",
                            CustomerName = "Андрій Савчук",
                            CustomerPhone = "+380501450067",
                            SessionId = 16,
                            Status = "Paid",
                            TicketCode = "CP-20260506-0007",
                            TotalPrice = 510m
                        },
                        new
                        {
                            Id = 8,
                            BookingDate = new DateTime(2026, 5, 6, 19, 5, 0, 0, DateTimeKind.Unspecified),
                            CustomerEmail = "yuliia.demo@cinemaplus.local",
                            CustomerName = "Юлія Бондар",
                            CustomerPhone = "+380631220078",
                            SessionId = 23,
                            Status = "Paid",
                            TicketCode = "CP-20260506-0008",
                            TotalPrice = 840m
                        });
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AgeRestriction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("AvailabilityDate")
                        .HasColumnType("date");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("AvailabilityStatus", "AvailabilityDate");

                    b.ToTable("Films", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = "12+",
                            AvailabilityDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailabilityStatus = "NowShowing",
                            Description = "Нова подорож Пандорою, де родина Саллі стикається з вогняним народом та небезпекою, що змінює майбутнє На'ві.",
                            DurationMinutes = 190,
                            Genre = "Фантастика",
                            PosterPath = "/source/avatar-poster.webp",
                            ReleaseYear = 2025,
                            Title = "Аватар: Вогонь і попіл (2025)"
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = "12+",
                            AvailabilityDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailabilityStatus = "NowShowing",
                            Description = "Боротьба за Арракіс виходить за межі однієї планети, а Пол Атрейдес робить вибір, що змінить майбутнє Імперіуму.",
                            DurationMinutes = 160,
                            Genre = "Фантастика",
                            PosterPath = "/source/images.jpeg",
                            ReleaseYear = 2026,
                            Title = "Дюна: Частина третя (2026)"
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = "16+",
                            AvailabilityDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailabilityStatus = "NowShowing",
                            Description = "Друзі з маленького міста зустрічаються з давнім страхом, який повертається у найтемніших образах.",
                            DurationMinutes = 135,
                            Genre = "Жахи",
                            PosterPath = "/source/it-poster.jpg",
                            ReleaseYear = 2017,
                            Title = "Воно"
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = "16+",
                            AvailabilityDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailabilityStatus = "NowShowing",
                            Description = "Нео відкриває правду про світ, у якому живе, та вступає у боротьбу з системою Матриці.",
                            DurationMinutes = 136,
                            Genre = "Фантастика",
                            PosterPath = "/source/matrix-poster.webp",
                            ReleaseYear = 1999,
                            Title = "Matrix"
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = "16+",
                            AvailabilityDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailabilityStatus = "NowShowing",
                            Description = "Остання битва друзів з Гокінса проти темряви, що загрожує їхньому місту та всьому світу.",
                            DurationMinutes = 120,
                            Genre = "Фантастика",
                            PosterPath = "/source/str-things-poster.jpg",
                            ReleaseYear = 2025,
                            Title = "Дивні дива: Фінал (2025)"
                        },
                        new
                        {
                            Id = 6,
                            AgeRestriction = "12+",
                            AvailabilityDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailabilityStatus = "NowShowing",
                            Description = "Команда супергероїв об'єднується, щоб зупинити загрозу, з якою неможливо впоратися поодинці.",
                            DurationMinutes = 143,
                            Genre = "Екшн",
                            PosterPath = "/source/avengers-poster.jpg",
                            ReleaseYear = 2012,
                            Title = "Avengers"
                        },
                        new
                        {
                            Id = 7,
                            AgeRestriction = "12+",
                            AvailabilityDate = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailabilityStatus = "ComingSoon",
                            Description = "Екіпаж вирушає до межі Сонячної системи, де на них чекає відкриття, здатне змінити історію людства.",
                            DurationMinutes = 118,
                            Genre = "Пригоди",
                            PosterPath = "/source/hero-img.jpg",
                            ReleaseYear = 2026,
                            Title = "Місія: Сонячний рубіж (2026)"
                        },
                        new
                        {
                            Id = 8,
                            AgeRestriction = "0+",
                            AvailabilityDate = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailabilityStatus = "ComingSoon",
                            Description = "Сімейна пригода про магічний ліс, дружбу та силу сміливого вибору.",
                            DurationMinutes = 104,
                            Genre = "Анімація",
                            PosterPath = "/source/form-hero.png",
                            ReleaseYear = 2026,
                            Title = "Лісова легенда (2026)"
                        });
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("RowsCount")
                        .HasColumnType("int");

                    b.Property<int>("SeatsPerRow")
                        .HasColumnType("int");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Halls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Зал 1",
                            RowsCount = 6,
                            SeatsPerRow = 10,
                            Technology = "2D"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Зал 2",
                            RowsCount = 8,
                            SeatsPerRow = 12,
                            Technology = "3D"
                        },
                        new
                        {
                            Id = 3,
                            Name = "VIP зал",
                            RowsCount = 5,
                            SeatsPerRow = 8,
                            Technology = "IMAX"
                        });
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("NotificationLogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            CreatedDate = new DateTime(2026, 5, 1, 10, 16, 0, 0, DateTimeKind.Unspecified),
                            Email = "client@cinemaplus.local",
                            Message = "Підтвердження бронювання CP-20260501-0001",
                            Status = "Emulated"
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 2,
                            CreatedDate = new DateTime(2026, 5, 2, 14, 6, 0, 0, DateTimeKind.Unspecified),
                            Email = "client@cinemaplus.local",
                            Message = "Підтвердження бронювання CP-20260502-0002",
                            Status = "Emulated"
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 3,
                            CreatedDate = new DateTime(2026, 5, 3, 18, 21, 0, 0, DateTimeKind.Unspecified),
                            Email = "marina.demo@cinemaplus.local",
                            Message = "Підтвердження бронювання CP-20260503-0003",
                            Status = "Emulated"
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 4,
                            CreatedDate = new DateTime(2026, 5, 4, 11, 41, 0, 0, DateTimeKind.Unspecified),
                            Email = "igor.demo@cinemaplus.local",
                            Message = "Підтвердження бронювання CP-20260504-0004",
                            Status = "Emulated"
                        },
                        new
                        {
                            Id = 5,
                            BookingId = 5,
                            CreatedDate = new DateTime(2026, 5, 5, 12, 6, 0, 0, DateTimeKind.Unspecified),
                            Email = "nataliia.demo@cinemaplus.local",
                            Message = "Підтвердження бронювання CP-20260505-0005",
                            Status = "Emulated"
                        },
                        new
                        {
                            Id = 6,
                            BookingId = 6,
                            CreatedDate = new DateTime(2026, 5, 5, 16, 36, 0, 0, DateTimeKind.Unspecified),
                            Email = "client@cinemaplus.local",
                            Message = "Підтвердження бронювання CP-20260505-0006",
                            Status = "Emulated"
                        },
                        new
                        {
                            Id = 7,
                            BookingId = 7,
                            CreatedDate = new DateTime(2026, 5, 6, 9, 11, 0, 0, DateTimeKind.Unspecified),
                            Email = "andrii.demo@cinemaplus.local",
                            Message = "Підтвердження бронювання CP-20260506-0007",
                            Status = "Emulated"
                        },
                        new
                        {
                            Id = 8,
                            BookingId = 8,
                            CreatedDate = new DateTime(2026, 5, 6, 19, 6, 0, 0, DateTimeKind.Unspecified),
                            Email = "yuliia.demo@cinemaplus.local",
                            Message = "Підтвердження бронювання CP-20260506-0008",
                            Status = "Emulated"
                        });
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "RowNumber", "SeatNumber")
                        .IsUnique();

                    b.ToTable("Seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HallId = 1,
                            RowNumber = 1,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            HallId = 1,
                            RowNumber = 1,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            HallId = 1,
                            RowNumber = 1,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            HallId = 1,
                            RowNumber = 1,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            HallId = 1,
                            RowNumber = 1,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            HallId = 1,
                            RowNumber = 1,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            HallId = 1,
                            RowNumber = 1,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            HallId = 1,
                            RowNumber = 1,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            HallId = 1,
                            RowNumber = 1,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 10,
                            HallId = 1,
                            RowNumber = 1,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 11,
                            HallId = 1,
                            RowNumber = 2,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 12,
                            HallId = 1,
                            RowNumber = 2,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 13,
                            HallId = 1,
                            RowNumber = 2,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 14,
                            HallId = 1,
                            RowNumber = 2,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 15,
                            HallId = 1,
                            RowNumber = 2,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 16,
                            HallId = 1,
                            RowNumber = 2,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 17,
                            HallId = 1,
                            RowNumber = 2,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 18,
                            HallId = 1,
                            RowNumber = 2,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 19,
                            HallId = 1,
                            RowNumber = 2,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 20,
                            HallId = 1,
                            RowNumber = 2,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 21,
                            HallId = 1,
                            RowNumber = 3,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 22,
                            HallId = 1,
                            RowNumber = 3,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 23,
                            HallId = 1,
                            RowNumber = 3,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 24,
                            HallId = 1,
                            RowNumber = 3,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 25,
                            HallId = 1,
                            RowNumber = 3,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 26,
                            HallId = 1,
                            RowNumber = 3,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 27,
                            HallId = 1,
                            RowNumber = 3,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 28,
                            HallId = 1,
                            RowNumber = 3,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 29,
                            HallId = 1,
                            RowNumber = 3,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 30,
                            HallId = 1,
                            RowNumber = 3,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 31,
                            HallId = 1,
                            RowNumber = 4,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 32,
                            HallId = 1,
                            RowNumber = 4,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 33,
                            HallId = 1,
                            RowNumber = 4,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 34,
                            HallId = 1,
                            RowNumber = 4,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 35,
                            HallId = 1,
                            RowNumber = 4,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 36,
                            HallId = 1,
                            RowNumber = 4,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 37,
                            HallId = 1,
                            RowNumber = 4,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 38,
                            HallId = 1,
                            RowNumber = 4,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 39,
                            HallId = 1,
                            RowNumber = 4,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 40,
                            HallId = 1,
                            RowNumber = 4,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 41,
                            HallId = 1,
                            RowNumber = 5,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 42,
                            HallId = 1,
                            RowNumber = 5,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 43,
                            HallId = 1,
                            RowNumber = 5,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 44,
                            HallId = 1,
                            RowNumber = 5,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 45,
                            HallId = 1,
                            RowNumber = 5,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 46,
                            HallId = 1,
                            RowNumber = 5,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 47,
                            HallId = 1,
                            RowNumber = 5,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 48,
                            HallId = 1,
                            RowNumber = 5,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 49,
                            HallId = 1,
                            RowNumber = 5,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 50,
                            HallId = 1,
                            RowNumber = 5,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 51,
                            HallId = 1,
                            RowNumber = 6,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 52,
                            HallId = 1,
                            RowNumber = 6,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 53,
                            HallId = 1,
                            RowNumber = 6,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 54,
                            HallId = 1,
                            RowNumber = 6,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 55,
                            HallId = 1,
                            RowNumber = 6,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 56,
                            HallId = 1,
                            RowNumber = 6,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 57,
                            HallId = 1,
                            RowNumber = 6,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 58,
                            HallId = 1,
                            RowNumber = 6,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 59,
                            HallId = 1,
                            RowNumber = 6,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 60,
                            HallId = 1,
                            RowNumber = 6,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 61,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 62,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 63,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 64,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 65,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 66,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 67,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 68,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 69,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 70,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 71,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 72,
                            HallId = 2,
                            RowNumber = 1,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 73,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 74,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 75,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 76,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 77,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 78,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 79,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 80,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 81,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 82,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 83,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 84,
                            HallId = 2,
                            RowNumber = 2,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 85,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 86,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 87,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 88,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 89,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 90,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 91,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 92,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 93,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 94,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 95,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 96,
                            HallId = 2,
                            RowNumber = 3,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 97,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 98,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 99,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 100,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 101,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 102,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 103,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 104,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 105,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 106,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 107,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 108,
                            HallId = 2,
                            RowNumber = 4,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 109,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 110,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 111,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 112,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 113,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 114,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 115,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 116,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 117,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 118,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 119,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 120,
                            HallId = 2,
                            RowNumber = 5,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 121,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 122,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 123,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 124,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 125,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 126,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 127,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 128,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 129,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 130,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 131,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 132,
                            HallId = 2,
                            RowNumber = 6,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 133,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 134,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 135,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 136,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 137,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 138,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 139,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 140,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 141,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 142,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 143,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 144,
                            HallId = 2,
                            RowNumber = 7,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 145,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 146,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 147,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 148,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 149,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 150,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 151,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 152,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 153,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 9
                        },
                        new
                        {
                            Id = 154,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 10
                        },
                        new
                        {
                            Id = 155,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 11
                        },
                        new
                        {
                            Id = 156,
                            HallId = 2,
                            RowNumber = 8,
                            SeatNumber = 12
                        },
                        new
                        {
                            Id = 157,
                            HallId = 3,
                            RowNumber = 1,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 158,
                            HallId = 3,
                            RowNumber = 1,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 159,
                            HallId = 3,
                            RowNumber = 1,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 160,
                            HallId = 3,
                            RowNumber = 1,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 161,
                            HallId = 3,
                            RowNumber = 1,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 162,
                            HallId = 3,
                            RowNumber = 1,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 163,
                            HallId = 3,
                            RowNumber = 1,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 164,
                            HallId = 3,
                            RowNumber = 1,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 165,
                            HallId = 3,
                            RowNumber = 2,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 166,
                            HallId = 3,
                            RowNumber = 2,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 167,
                            HallId = 3,
                            RowNumber = 2,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 168,
                            HallId = 3,
                            RowNumber = 2,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 169,
                            HallId = 3,
                            RowNumber = 2,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 170,
                            HallId = 3,
                            RowNumber = 2,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 171,
                            HallId = 3,
                            RowNumber = 2,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 172,
                            HallId = 3,
                            RowNumber = 2,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 173,
                            HallId = 3,
                            RowNumber = 3,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 174,
                            HallId = 3,
                            RowNumber = 3,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 175,
                            HallId = 3,
                            RowNumber = 3,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 176,
                            HallId = 3,
                            RowNumber = 3,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 177,
                            HallId = 3,
                            RowNumber = 3,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 178,
                            HallId = 3,
                            RowNumber = 3,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 179,
                            HallId = 3,
                            RowNumber = 3,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 180,
                            HallId = 3,
                            RowNumber = 3,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 181,
                            HallId = 3,
                            RowNumber = 4,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 182,
                            HallId = 3,
                            RowNumber = 4,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 183,
                            HallId = 3,
                            RowNumber = 4,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 184,
                            HallId = 3,
                            RowNumber = 4,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 185,
                            HallId = 3,
                            RowNumber = 4,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 186,
                            HallId = 3,
                            RowNumber = 4,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 187,
                            HallId = 3,
                            RowNumber = 4,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 188,
                            HallId = 3,
                            RowNumber = 4,
                            SeatNumber = 8
                        },
                        new
                        {
                            Id = 189,
                            HallId = 3,
                            RowNumber = 5,
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = 190,
                            HallId = 3,
                            RowNumber = 5,
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = 191,
                            HallId = 3,
                            RowNumber = 5,
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = 192,
                            HallId = 3,
                            RowNumber = 5,
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = 193,
                            HallId = 3,
                            RowNumber = 5,
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = 194,
                            HallId = 3,
                            RowNumber = 5,
                            SeatNumber = 6
                        },
                        new
                        {
                            Id = 195,
                            HallId = 3,
                            RowNumber = 5,
                            SeatNumber = 7
                        },
                        new
                        {
                            Id = 196,
                            HallId = 3,
                            RowNumber = 5,
                            SeatNumber = 8
                        });
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("SessionTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("SessionTime");

                    b.HasIndex("FilmId", "HallId", "SessionTime")
                        .IsUnique();

                    b.ToTable("Sessions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilmId = 1,
                            HallId = 1,
                            Price = 180m,
                            SessionTime = new DateTime(2026, 5, 5, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            FilmId = 1,
                            HallId = 1,
                            Price = 180m,
                            SessionTime = new DateTime(2026, 5, 5, 12, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            FilmId = 1,
                            HallId = 2,
                            Price = 220m,
                            SessionTime = new DateTime(2026, 5, 5, 17, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            FilmId = 1,
                            HallId = 2,
                            Price = 220m,
                            SessionTime = new DateTime(2026, 5, 5, 19, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            FilmId = 2,
                            HallId = 1,
                            Price = 180m,
                            SessionTime = new DateTime(2026, 5, 6, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            FilmId = 2,
                            HallId = 1,
                            Price = 180m,
                            SessionTime = new DateTime(2026, 5, 6, 12, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            FilmId = 2,
                            HallId = 2,
                            Price = 220m,
                            SessionTime = new DateTime(2026, 5, 6, 15, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            FilmId = 2,
                            HallId = 2,
                            Price = 220m,
                            SessionTime = new DateTime(2026, 5, 6, 19, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            FilmId = 3,
                            HallId = 1,
                            Price = 160m,
                            SessionTime = new DateTime(2026, 5, 7, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            FilmId = 3,
                            HallId = 1,
                            Price = 160m,
                            SessionTime = new DateTime(2026, 5, 7, 12, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            FilmId = 3,
                            HallId = 2,
                            Price = 190m,
                            SessionTime = new DateTime(2026, 5, 7, 15, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            FilmId = 3,
                            HallId = 2,
                            Price = 190m,
                            SessionTime = new DateTime(2026, 5, 7, 17, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            FilmId = 4,
                            HallId = 1,
                            Price = 160m,
                            SessionTime = new DateTime(2026, 5, 8, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            FilmId = 4,
                            HallId = 2,
                            Price = 190m,
                            SessionTime = new DateTime(2026, 5, 8, 15, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            FilmId = 4,
                            HallId = 2,
                            Price = 190m,
                            SessionTime = new DateTime(2026, 5, 8, 17, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            FilmId = 5,
                            HallId = 1,
                            Price = 170m,
                            SessionTime = new DateTime(2026, 5, 9, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            FilmId = 5,
                            HallId = 1,
                            Price = 170m,
                            SessionTime = new DateTime(2026, 5, 9, 12, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            FilmId = 5,
                            HallId = 2,
                            Price = 200m,
                            SessionTime = new DateTime(2026, 5, 9, 15, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            FilmId = 5,
                            HallId = 2,
                            Price = 200m,
                            SessionTime = new DateTime(2026, 5, 9, 17, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            FilmId = 5,
                            HallId = 3,
                            Price = 260m,
                            SessionTime = new DateTime(2026, 5, 9, 19, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            FilmId = 6,
                            HallId = 1,
                            Price = 180m,
                            SessionTime = new DateTime(2026, 5, 10, 12, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            FilmId = 6,
                            HallId = 2,
                            Price = 220m,
                            SessionTime = new DateTime(2026, 5, 10, 15, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            FilmId = 6,
                            HallId = 3,
                            Price = 280m,
                            SessionTime = new DateTime(2026, 5, 10, 19, 45, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@cinemaplus.local",
                            FullName = "Адміністратор CinemaPlus",
                            PasswordHash = "PBKDF2-SHA256$100000$Q2luZW1hUGx1c0FkbWluU2VlZFNhbHQyMDI2$QH4wb86t1iJR1VcbnplnhpgMk7Q4ROIyNmqOM6m5+Sg=",
                            Phone = "+380501112233",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "client@cinemaplus.local",
                            FullName = "Олена Коваль",
                            PasswordHash = "PBKDF2-SHA256$100000$Q2luZW1hUGx1c0NsaWVudFNlZWRTYWx0MjAyNg==$Np9+ovw8byxBN8DeP7YEN+iDXUE+4HGEA0+05IxctiE=",
                            Phone = "+380672223344",
                            Role = "Client"
                        });
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.BookedSeat", b =>
                {
                    b.HasOne("CinemaPlus.CinemaWebApp.Models.Booking", "Booking")
                        .WithMany("BookedSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaPlus.CinemaWebApp.Models.Seat", "Seat")
                        .WithMany("BookedSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaPlus.CinemaWebApp.Models.Session", "Session")
                        .WithMany("BookedSeats")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Booking", b =>
                {
                    b.HasOne("CinemaPlus.CinemaWebApp.Models.Session", "Session")
                        .WithMany("Bookings")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaPlus.CinemaWebApp.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.NotificationLog", b =>
                {
                    b.HasOne("CinemaPlus.CinemaWebApp.Models.Booking", "Booking")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Seat", b =>
                {
                    b.HasOne("CinemaPlus.CinemaWebApp.Models.Hall", "Hall")
                        .WithMany("Seats")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Session", b =>
                {
                    b.HasOne("CinemaPlus.CinemaWebApp.Models.Film", "Film")
                        .WithMany("Sessions")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaPlus.CinemaWebApp.Models.Hall", "Hall")
                        .WithMany("Sessions")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Booking", b =>
                {
                    b.Navigation("BookedSeats");

                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Film", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Hall", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Seat", b =>
                {
                    b.Navigation("BookedSeats");
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.Session", b =>
                {
                    b.Navigation("BookedSeats");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CinemaPlus.CinemaWebApp.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
